services:
  ekbooks:
    build:
      context: ./shared-wordpress-image
      dockerfile: Dockerfile
    image: local/wordpress-redis:ekbooks
    container_name: wp_ekbooks
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: MariaDB-Official
      WORDPRESS_DB_USER: ekbooks_user
      WORDPRESS_DB_PASSWORD: AEVEjIztP24vca
      WORDPRESS_DB_NAME: ekbooks_db
      WORDPRESS_TABLE_PREFIX: wp_ek_
      TZ: America/Toronto
    volumes:
      - ./ekbooks/html:/var/www/html
    networks:
      - makprox
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ekbooks.rule=Host(`ekbooks.ca`)"
      - "traefik.http.routers.ekbooks.entrypoints=websecure"
      - "traefik.http.routers.ekbooks.tls=true"
      - "traefik.http.routers.ekbooks.tls.certresolver=cloudflare"

  taxcat:
    build:
      context: ./shared-wordpress-image
      dockerfile: Dockerfile
    image: local/wordpress-redis:taxcat
    container_name: wp_taxcat
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: MariaDB-Official
      WORDPRESS_DB_USER: taxcat_user
      WORDPRESS_DB_PASSWORD: CpfmAgoNDN7Uym
      WORDPRESS_DB_NAME: taxcat_db
      WORDPRESS_TABLE_PREFIX: wp_tc_
      TZ: America/Toronto
    volumes:
      - ./taxcat/html:/var/www/html
    networks:
      - webstack_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.taxcat.rule=Host(`taxcat.ca`)"
      - "traefik.http.routers.taxcat.entrypoints=websecure"
      - "traefik.http.routers.taxcat.tls=true"
      - "traefik.http.routers.taxcat.tls.certresolver=cloudflare"

networks:
  makprox:
    external: true