#!/bin/bash

# TaxCat Unraid Installation Script
# This script handles the initial setup of TaxCat on Unraid

set -e

echo "🐱 TaxCat Unraid Installation Script"
echo "====================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
UNRAID_IP=${1:-"localhost"}
APP_NAME="taxcat-app"
COMPOSE_FILE="docker-compose.unraid.yml"

echo -e "${YELLOW}📋 Installation Summary:${NC}"
echo "Target IP: $UNRAID_IP"
echo "Application: $APP_NAME"
echo "Compose File: $COMPOSE_FILE"
echo ""

# Check if running on Unraid
check_unraid() {
    if [ -f "/etc/unraid-version" ]; then
        echo -e "${GREEN}✅ Unraid system detected${NC}"
        UNRAID_VERSION=$(cat /etc/unraid-version | cut -d'=' -f2)
        echo "Unraid Version: $UNRAID_VERSION"
    else
        echo -e "${YELLOW}⚠️  Not running on Unraid, but continuing...${NC}"
    fi
}

# Check Docker availability
check_docker() {
    echo -e "${YELLOW}🔍 Checking Docker installation...${NC}"
    if command -v docker &> /dev/null; then
        echo -e "${GREEN}✅ Docker is installed${NC}"
        docker --version
    else
        echo -e "${RED}❌ Docker is not installed. Please install Docker first.${NC}"
        exit 1
    fi

    if command -v docker-compose &> /dev/null; then
        echo -e "${GREEN}✅ Docker Compose is installed${NC}"
        docker-compose --version
    else
        echo -e "${RED}❌ Docker Compose is not installed. Please install Docker Compose first.${NC}"
        exit 1
    fi
}

# Create necessary directories
create_directories() {
    echo -e "${YELLOW}📁 Creating application directories...${NC}"
    
    mkdir -p ./data/{uploads,logs}
    mkdir -p ./config
    mkdir -p ./nginx/ssl
    mkdir -p ./prometheus
    mkdir -p ./grafana/provisioning
    
    chmod 755 ./data ./data/uploads ./data/logs
    echo -e "${GREEN}✅ Directories created${NC}"
}

# Create environment file
create_env_file() {
    echo -e "${YELLOW}⚙️  Creating environment configuration...${NC}"
    
    if [ ! -f ".env.local" ]; then
        cat > .env.local << EOF
# TaxCat Environment Configuration
# Generated by install script

# Database Configuration
DATABASE_URL="postgresql://taxcat_user:secure_password123@postgres:5432/taxcat_prod"

# Application Configuration  
NODE_ENV=production
PORT=3000
HOSTNAME=0.0.0.0
NEXT_TELEMETRY_DISABLED=1

# Application URLs
NEXT_PUBLIC_APP_URL=http://$UNRAID_IP:3000
NEXTAUTH_URL=http://$UNRAID_IP:3000
NEXTAUTH_SECRET=generate-a-32-format-super-secret-key-here-xyz123

# CMS Admin Configuration
CMS_ADMIN_EMAIL=admin@taxcat.ca
CMS_ADMIN_PASSWORD=changeme_admin_password_123

# Redis Configuration
REDIS_URL=redis://:redis_password_123@redis:6379

# External Services (Optional - add your keys)
STRIPE_SECRET_KEY=""
STRIPE_PUBLISHABLE_KEY=""
AWS_S3_BUCKET=""
AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""

# Monitoring (Optional)
SENTRY_DSN=""
EOF
        
        echo -e "${GREEN}✅ Environment file created: .env.local${NC}"
        echo -e "${YELLOW}🔒 IMPORTANT: Please update passwords in .env.local before starting services!${NC}"
    else
        echo -e "${YELLOW}⚠️  Environment file already exists, skipping...${NC}"
    fi
}

# Generate random secrets
generate_secrets() {
    echo -e "${YELLOW}🔐 Generating secure secrets...${NC}"
    
    # Generate a random 32-character secret
    RANDOM_SECRET=$(openssl rand -base64 32 | tr -d '\n')
    DATABASE_PASSWORD=$(openssl rand -base64 16 | tr -d '\n')
    REDIS_PASSWORD=$(openssl rand -base64 16 | tr -d '\n')
    
    # Update .env.local with generated secrets
    sed -i "s/generate-a-32-format-super-secret-key-here-xyz123/$RANDOM_SECRET/" .env.local
    sed -i "s/secure_password123/$DATABASE_PASSWORD/" .env.local
    sed -i "s/redis_password_123/$REDIS_PASSWORD/" .env.local
    sed -i "s/changeme_admin_password_123/admin_$(openssl rand -hex 8)/" .env.local
    
    echo -e "${GREEN}✅ Secrets generated and updated${NC}"
}

# Build and start services
start_services() {
    echo -e "${YELLOW}🐳 Building and starting Docker services...${NC}"
    
    # Stop any existing services
    docker-compose -f $COMPOSE_FILE down 2>/dev/null || true
    
    # Build the application
    echo "Building TaxCat application..."
    docker-compose -f $COMPOSE_FILE build --no-cache taxcat-app
    
    # Start all services
    echo "Starting all services..."
    docker-compose -f $COMPOSE_FILE up -d
    
    echo -e "${GREEN}✅ Services started successfully!${NC}"
}

# Wait for services to be ready
wait_for_services() {
    echo -e "${YELLOW}⏳ Waiting for services to be ready...${NC}"
    
    # Wait for database
    echo "Waiting for PostgreSQL..."
    until docker-compose -f $COMPOSE_FILE exec postgres pg_isready -U taxcat_user -d taxcat_prod 2>/dev/null; do
        sleep 2
    done
    echo -e "${GREEN}✅ PostgreSQL is ready${NC}"
    
    # Wait for Redis
    echo "Waiting for Redis..."
    until docker-compose -f $COMPOSE_FILE exec redis redis-cli ping 2>/dev/null; do
        sleep 2
    done
    echo -e "${GREEN}✅ Redis is ready${NC}"
    
    # Wait for application
    echo "Waiting for TaxCat application..."
    until curl -f http://localhost:3000/api/health 2>/dev/null; do
        sleep 5
    done
    echo -e "${GREEN}✅ TaxCat application is ready!${NC}"
}

# Show service status
show_status() {
    echo -e "${YELLOW}📊 Service Status:${NC}"
    docker-compose -f $COMPOSE_FILE ps
    
    echo -e "${YELLOW}🌐 Access Information:${NC}"
    echo "TaxCat Application: http://$UNRAID_IP:3000"
    echo "Health Check: http://$UNRAID_IP:3000/api/health"
    echo ""
    echo -e "${YELLOW}📝 Next Steps:${NC}"
    echo "1. Open http://$UNRAID_IP:3000 in your browser"
    echo "2. Register your first admin account"
    echo "3. Login and start using TaxCat!"
    echo ""
    echo -e "${YELLOW}🔧 Management Commands:${NC}"
    echo "View logs: docker-compose -f $COMPOSE_FILE logs -f"
    echo "Restart: docker-compose -f $COMPOSE_FILE restart"
    echo "Stop: docker-compose -f $COMPOSE_FILE down"
}

# Main installation process
main() {
    echo -e "${YELLOW}Starting TaxCat installation...${NC}"
    
    check_unraid
    check_docker
    create_directories
    create_env_file
    generate_secrets
    start_services
    wait_for_services
    show_status
    
    echo -e "${GREEN}🎉 TaxCat installation completed successfully!${NC}"
    echo -e "${GREEN}🐱 Welcome to TaxCat on Unraid!${NC}"
}

# Show help
show_help() {
    echo "Usage: $0 [UNRAID_IP]"
    echo ""
    echo "Arguments:"
    echo "  UNRAID_IP    IP address of your Unraid server (default: localhost)"
    echo ""
    echo "Examples:"
    echo "  $0                           # Install on localhost"
    echo "  $0 192.168.1.100            # Install on Unraid server at 192.168.1.100"
    echo ""
    echo "This script will:"
    echo "- Check system requirements"
    echo "- Create necessary directories"
    echo "- Generate secure environment configuration"
    echo "- Build and start all Docker services"
    echo "- Wait for services to be ready"
    echo "- Show setup completion status"
}

# Handle command line arguments
case "${1:-}" in
    -h|--help)
        show_help
        exit 0
        ;;
    *)
        main
        ;;
esac
